#!/bin/bash
#
# This script will only run on a computer using the IP
# address: 128.100.3.15.
#
# This auto-generated script was downloaded from http://iotta.snia.org.
# It will download the 110 subtraces of IBM Object Store
#
echo "Downloading the 110 subtraces of IBM Object Store" 1>&2
cookies=$(mktemp)
cat >> $cookies << 'EOF'
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by iotta.snia.org! Edit at your own risk.

.iotta.snia.org	TRUE	/	FALSE	0	infodigest	d867ec79279fa6db56d54a1cf197ba3d54d5e2ca
.iotta.snia.org	TRUE	/	FALSE	0	legal	true
.iotta.snia.org	TRUE	/	FALSE	0	id	1116656
.iotta.snia.org	TRUE	/	FALSE	0	user_ip	128.100.3.15
EOF

if which wget >/dev/null 2>&1; then
  useWGET=true
elif which curl >/dev/null 2>&1; then
  useCURL=true
else
  echo "Couldn't find either wget or curl. Please install one of them" 1>&2
  exit 1
fi

checkForError() {
  delete=false
  if $useWGET && (( $1 == 2 || $1 == 3 || $1 == 5 || $1 == 7 || $1 == 8 ))
  then
    delete=true
  elif $useWGET && [ ! -s "$2" ]
  then
    delete=true
  elif $useCURL && (( $1 == 22 || $1 == 36 ))
  then
    delete=true
  fi
}

downloadFile() {
  file=$1
  id=$2
  url="http://server3.iotta.snia.org/traces/key-value/$id/download?type=file&sType="
  if $useWGET; then
    wget -q --content-on-error --load-cookies=$cookies -O "$file" -c "$url""wget"
    error=$?
  elif $useCURL; then
    curl -s -f -b $cookies -o "$file" -C - -L "$url""curl"
    error=$?
    if [ $error -eq 22 ]; then
      curl -s -b $cookies -o "$file" -C - -L "$url""curl"
    fi
  fi

  if [ $error -eq 0 ]; then
    echo "Finished Downloading $file"
  else
    checkForError $error "$file"
    downloadLink="http://iotta.snia.org/downloaderinfos/new?trace_id=36305&type=subtracesViaScript&sType=&came_from=iotta.snia.org"
    if $delete; then
      echo "There was an error downloading the file ($file)"
      if grep "internal iotta error: ip mismatch" "$file" > /dev/null; then
        echo "This script will only run on a computer with the IP address 128.100.3.15."
        grep "Your current IP address is" "$file"
        echo "Please use the following link to fill out the download license form with your current IP address and run the new script:"
        echo "$downloadLink"
      elif grep "internal iotta error: invalid cookie" "$file" > /dev/null; then
        echo "Invalid cookie, please use the following link to fill out the form and try again:"
        echo "$downloadLink"
      fi
      rm -f "$file"
    else
      echo "$file was only partially downloaded."
    fi
    echo "Stopping..."
    exit 1
  fi
}

downloadFile "IBMObjectStoreTrace000Part0.tgz" 36308
downloadFile "IBMObjectStoreTrace001Part0.tgz" 36311
downloadFile "IBMObjectStoreTrace002Part0.tgz" 36314
downloadFile "IBMObjectStoreTrace003Part0.tgz" 36317
downloadFile "IBMObjectStoreTrace004Part0.tgz" 36320
downloadFile "IBMObjectStoreTrace005Part0.tgz" 36323
downloadFile "IBMObjectStoreTrace005Part1.tgz" 36326
downloadFile "IBMObjectStoreTrace005Part2.tgz" 36329
downloadFile "IBMObjectStoreTrace005Part3.tgz" 36332
downloadFile "IBMObjectStoreTrace005Part4.tgz" 36335
downloadFile "IBMObjectStoreTrace005Part5.tgz" 36338
downloadFile "IBMObjectStoreTrace005Part6.tgz" 36341
downloadFile "IBMObjectStoreTrace006Part0.tgz" 36344
downloadFile "IBMObjectStoreTrace007Part0.tgz" 36347
downloadFile "IBMObjectStoreTrace008Part0.tgz" 36350
downloadFile "IBMObjectStoreTrace009Part0.tgz" 36353
downloadFile "IBMObjectStoreTrace010Part0.tgz" 36356
downloadFile "IBMObjectStoreTrace011Part0.tgz" 36359
downloadFile "IBMObjectStoreTrace012Part0.tgz" 36362
downloadFile "IBMObjectStoreTrace013Part0.tgz" 36365
downloadFile "IBMObjectStoreTrace014Part0.tgz" 36368
downloadFile "IBMObjectStoreTrace015Part0.tgz" 36371
downloadFile "IBMObjectStoreTrace016Part0.tgz" 36374
downloadFile "IBMObjectStoreTrace017Part0.tgz" 36377
downloadFile "IBMObjectStoreTrace018Part0.tgz" 36380
downloadFile "IBMObjectStoreTrace018Part1.tgz" 36383
downloadFile "IBMObjectStoreTrace018Part2.tgz" 36386
downloadFile "IBMObjectStoreTrace019Part0.tgz" 36389
downloadFile "IBMObjectStoreTrace020Part0.tgz" 36392
downloadFile "IBMObjectStoreTrace021Part0.tgz" 36395
downloadFile "IBMObjectStoreTrace022Part0.tgz" 36398
downloadFile "IBMObjectStoreTrace023Part0.tgz" 36401
downloadFile "IBMObjectStoreTrace024Part0.tgz" 36404
downloadFile "IBMObjectStoreTrace025Part0.tgz" 36407
downloadFile "IBMObjectStoreTrace026Part0.tgz" 36410
downloadFile "IBMObjectStoreTrace027Part0.tgz" 36413
downloadFile "IBMObjectStoreTrace028Part0.tgz" 36416
downloadFile "IBMObjectStoreTrace029Part0.tgz" 36419
downloadFile "IBMObjectStoreTrace030Part0.tgz" 36422
downloadFile "IBMObjectStoreTrace031Part0.tgz" 36425
downloadFile "IBMObjectStoreTrace032Part0.tgz" 36428
downloadFile "IBMObjectStoreTrace033Part0.tgz" 36431
downloadFile "IBMObjectStoreTrace034Part0.tgz" 36434
downloadFile "IBMObjectStoreTrace035Part0.tgz" 36437
downloadFile "IBMObjectStoreTrace036Part0.tgz" 36440
downloadFile "IBMObjectStoreTrace037Part0.tgz" 36443
downloadFile "IBMObjectStoreTrace038Part0.tgz" 36446
downloadFile "IBMObjectStoreTrace039Part0.tgz" 36449
downloadFile "IBMObjectStoreTrace040Part0.tgz" 36452
downloadFile "IBMObjectStoreTrace041Part0.tgz" 36455
downloadFile "IBMObjectStoreTrace042Part0.tgz" 36458
downloadFile "IBMObjectStoreTrace043Part0.tgz" 36461
downloadFile "IBMObjectStoreTrace044Part0.tgz" 36464
downloadFile "IBMObjectStoreTrace045Part0.tgz" 36467
downloadFile "IBMObjectStoreTrace046Part0.tgz" 36470
downloadFile "IBMObjectStoreTrace047Part0.tgz" 36473
downloadFile "IBMObjectStoreTrace048Part0.tgz" 36476
downloadFile "IBMObjectStoreTrace049Part0.tgz" 36479
downloadFile "IBMObjectStoreTrace050Part0.tgz" 36482
downloadFile "IBMObjectStoreTrace051Part0.tgz" 36485
downloadFile "IBMObjectStoreTrace052Part0.tgz" 36488
downloadFile "IBMObjectStoreTrace053Part0.tgz" 36491
downloadFile "IBMObjectStoreTrace054Part0.tgz" 36494
downloadFile "IBMObjectStoreTrace055Part0.tgz" 36497
downloadFile "IBMObjectStoreTrace056Part0.tgz" 36500
downloadFile "IBMObjectStoreTrace057Part0.tgz" 36503
downloadFile "IBMObjectStoreTrace058Part0.tgz" 36506
downloadFile "IBMObjectStoreTrace058Part1.tgz" 36509
downloadFile "IBMObjectStoreTrace059Part0.tgz" 36512
downloadFile "IBMObjectStoreTrace060Part0.tgz" 36515
downloadFile "IBMObjectStoreTrace061Part0.tgz" 36518
downloadFile "IBMObjectStoreTrace062Part0.tgz" 36521
downloadFile "IBMObjectStoreTrace063Part0.tgz" 36524
downloadFile "IBMObjectStoreTrace063Part1.tgz" 36527
downloadFile "IBMObjectStoreTrace063Part2.tgz" 36530
downloadFile "IBMObjectStoreTrace063Part3.tgz" 36533
downloadFile "IBMObjectStoreTrace064Part0.tgz" 36536
downloadFile "IBMObjectStoreTrace065Part0.tgz" 36539
downloadFile "IBMObjectStoreTrace066Part0.tgz" 36542
downloadFile "IBMObjectStoreTrace067Part0.tgz" 36545
downloadFile "IBMObjectStoreTrace068Part0.tgz" 36548
downloadFile "IBMObjectStoreTrace069Part0.tgz" 36551
downloadFile "IBMObjectStoreTrace070Part0.tgz" 36554
downloadFile "IBMObjectStoreTrace071Part0.tgz" 36557
downloadFile "IBMObjectStoreTrace072Part0.tgz" 36560
downloadFile "IBMObjectStoreTrace073Part0.tgz" 36563
downloadFile "IBMObjectStoreTrace074Part0.tgz" 36566
downloadFile "IBMObjectStoreTrace075Part0.tgz" 36569
downloadFile "IBMObjectStoreTrace076Part0.tgz" 36572
downloadFile "IBMObjectStoreTrace077Part0.tgz" 36575
downloadFile "IBMObjectStoreTrace078Part0.tgz" 36578
downloadFile "IBMObjectStoreTrace079Part0.tgz" 36581
downloadFile "IBMObjectStoreTrace080Part0.tgz" 36584
downloadFile "IBMObjectStoreTrace081Part0.tgz" 36587
downloadFile "IBMObjectStoreTrace082Part0.tgz" 36590
downloadFile "IBMObjectStoreTrace083Part0.tgz" 36593
downloadFile "IBMObjectStoreTrace084Part0.tgz" 36596
downloadFile "IBMObjectStoreTrace085Part0.tgz" 36599
downloadFile "IBMObjectStoreTrace086Part0.tgz" 36602
downloadFile "IBMObjectStoreTrace087Part0.tgz" 36605
downloadFile "IBMObjectStoreTrace088Part0.tgz" 36608
downloadFile "IBMObjectStoreTrace089Part0.tgz" 36611
downloadFile "IBMObjectStoreTrace090Part0.tgz" 36614
downloadFile "IBMObjectStoreTrace091Part0.tgz" 36617
downloadFile "IBMObjectStoreTrace092Part0.tgz" 36620
downloadFile "IBMObjectStoreTrace093Part0.tgz" 36623
downloadFile "IBMObjectStoreTrace094Part0.tgz" 36626
downloadFile "IBMObjectStoreTrace095Part0.tgz" 36629
downloadFile "IBMObjectStoreTrace096Part0.tgz" 36632
downloadFile "IBMObjectStoreTrace097Part0.tgz" 36635

echo "Finished All Downloads"
rm -f $cookies
